const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const envConfig = {};

// Default fallbacks if keys are not set
const defaults = {
  API_URL: 'https://fakestoreapi.com',
  LOGIN_USERNAME: '',
  LOGIN_PASSWORD: ''
};

if (fs.existsSync(envPath)) {
  console.log('Found .env file. Loading configuration...');
  const envFile = fs.readFileSync(envPath, 'utf8');
  envFile.split(/\r?\n/).forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      return;
    }
    const index = trimmed.indexOf('=');
    if (index > 0) {
      const key = trimmed.substring(0, index).trim();
      let value = trimmed.substring(index + 1).trim();
      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        value = value.substring(1, value.length - 1);
      }
      envConfig[key] = value;
    }
  });
} else {
  console.log('.env file not found. Using system environment variables or defaults.');
}

const API_URL = process.env.API_URL || envConfig.API_URL || defaults.API_URL;
const LOGIN_USERNAME = process.env.LOGIN_USERNAME || envConfig.LOGIN_USERNAME || defaults.LOGIN_USERNAME;
const LOGIN_PASSWORD = process.env.LOGIN_PASSWORD || envConfig.LOGIN_PASSWORD || defaults.LOGIN_PASSWORD;

const envDir = path.join(__dirname, 'src', 'environments');
if (!fs.existsSync(envDir)) {
  fs.mkdirSync(envDir, { recursive: true });
}

const environmentFileContent = `// This file is auto-generated by set-env.js
export const environment = {
  production: true,
  apiUrl: '${API_URL}',
  loginUsername: '${LOGIN_USERNAME}',
  loginPassword: '${LOGIN_PASSWORD}'
};
`;

const environmentDevFileContent = `// This file is auto-generated by set-env.js
export const environment = {
  production: false,
  apiUrl: '${API_URL}',
  loginUsername: '${LOGIN_USERNAME}',
  loginPassword: '${LOGIN_PASSWORD}'
};
`;

fs.writeFileSync(path.join(envDir, 'environment.ts'), environmentFileContent);
fs.writeFileSync(path.join(envDir, 'environment.development.ts'), environmentDevFileContent);

console.log(`Angular environment files generated successfully in ${envDir}`);
